swagger: "2.0"
info:
  description: Alexandria is a simple little card catalogue webapp with a terribly pretentious name.
  title: Alexandria API
  version: "0.0.1-preview"
  contact:
    name: Alexandria API Team
    url: https://github.com/hawkw/Alexandria
basePath: /api

paths:
  /books:
    get:
      description: Get a list of all books.
      produces:
        - application/json
      parameters:
        - name: test
          in: path
        - name: offset
          #description: The starting number of the books to retrieve
          #in: path
          #required: false
          #type: integer
          #default: 0
        - name: count
          #description: The number of books to retrieve
          #in: path
          #required: false
          #type: integer
          #default: 10
      responses:
        200:
          description: Test
          #description: List all books
          #schema:
            #title: Books
            #type: array
            #item:
              #$ref: '#/definitions/Book'
    post:
      description: Create a new book.
      produces:
        - application/json
      parameters:
        - name: book
          in: body
          description: Add book to library.
          required: true
          schema:
            $ref: '#/definitions/Book'
      responses:
        '201':
          description: Book created.
          schema:
            $ref: '#/definitions/Book'
        

#definitions:
#  Book:
#    properties:
#      isbn:
#        type: string
#      title:
#        type: string
#      author:
#        type: string
#      test:
#        type: string
  