sudo: false
language: scala
scala:
- 2.11.6
- 2.11.4
- 2.10.4
script:
- sbt compile
- sbt clean coverage test
- sbt coverageReport
- sbt coverageAggregate
- sbt codacyCoverage
branches:
  except:
    - api-spec
env:
  global:
    secure: em6vWCgSjjgJ7rPn3N0YH8qKA+Y3B5H6i88YVmQL/Hwh0D34/3NBwIQeNc3XDVJZP/012s8BojnBStOs4G1mHJH7vseoNErjBbsZLp0vXdec7Aw9Vum9jp/D2UTou5BKL8lD9vABsk5HSULNM3Si8M//JsTEdrnX+Rcd7G3S4ERm1pOSIBvCQeWF7WKyZNPyMzxZ3JGxkPIlqS9DWj3KGfixfCVAfsA2DHt39NjwSIwPXGENN8KiTSivFq/RyxrDqwQy1PqdzThN6xXkpvbw663Vi7IprD6GcyuAA5W0+gCN8Kcbv/ZJhTKbaoBPXP6in5Ig48qpwRhRJuGquAqua6hQ3NoaQLSsBo2mQMrz9fH0KSeKBk7EWYc9u1QSRwL8ef6rjzXxd0bGgLSNfqux9EBAneF4Bw1W2KbIV15KKHEqqlJwfkGABTi/4cxLmChUmFhYbV3Kg7g4UZkoe7PzdbJB14Le+ZBRRT98MCvytQT/M7x6kqC0zaEy3PQmvcEfR7MXSNrUdGdYqkdU619PuRiS8cv2YqxXdFevFm0c1eyUAb9hjQkD2hrK62xVKTs51C00BUl3qPED+Dz5tNfU3tyAuM9S4vLtWuKCA01B4cX1Gfrc9K25vU/Hb5qQrFBbm+Dl0p60E5VAb01DcXS2hIFiNj23Ir9aNfuFG9OEqV8=
notifications:
  slack:
    secure: OPuCsKLxD5tqFqIyDTA6KQniJg1sfK+pIwMmY0G6Qc6jBXfXqiRNu+jdWsQVGQrK5z6aypPnjXE0hvDJLLwFkYXh+K2IOBMOGLohpBRcZSI/FX094UbGJw+ixIx778q1KC95/ja2ghs7iQqoYoUkvuKS2BgHIvrcpEyLtRIGhKc1ILpnA1RwtSBqIHpxavoUjr3UkbeIHLSlxYX2I+3GmZGSmnlkPINoXrDvoMECYj4dwyS4ngjg1WaUNDpFlca3N/45xrn8j+suBcP3AjQDf/tvF2jxQNPbv+fCybeaQIhjK3RIy3ZfdJliz5h4B+/0TCnRvYf1ZlVukzQTpjdJuFhV40Cb7m7R7NTWt3bYZ5RbrQvyX4eynF3Ft1X+hfIugL6UcXagEwwDxtSxhlOMoiR/h7g3WjsbrLceAQ79bn8WVpWyEMI2BB4+bjU6OPRPIbfquKlr3zzoT6jgIO1oQ+xFzsp5FvmfdjQPi+KjgyAZVAkkHjM96wBY0w47JA9J2uLvvHoX/tJj0zGTOU5nxi1TasnG//7BZ3M4vWlUR25nLfMz7hI4fszv/a6J6MfgPHNOxxuXPPOt92+Pmz2+IO8XbxcAtkrbYo01Sh38NzYtNj85qUPihV9zJOtx7igomwxR1jJWNjp2Oy/+/2Eg8+FpcJsfXgXUFbZq5cfg8Nk=
